ALTER SESSION SET "_oracle_script" = TRUE;

-- 1
CREATE TABLESPACE TS_GAF 
DATAFILE 'C:\5sem\database\TS_GAF.dbf' SIZE 7M 
AUTOEXTEND ON NEXT 5M MAXSIZE 30M;

-- 2
CREATE TEMPORARY TABLESPACE TS_GAF_TEMP 
TEMPFILE 'C:\5sem\database\TS_GAF_TEMP.dbf' SIZE 5M 
AUTOEXTEND ON NEXT 3M MAXSIZE 20M
EXTENT MANAGEMENT LOCAL;

-- 3
SELECT TABLESPACE_NAME, STATUS, CONTENTS 
FROM DBA_TABLESPACES;

SELECT FILE_NAME, TABLESPACE_NAME, BYTES/1024/1024 AS SIZE_MB, AUTOEXTENSIBLE 
FROM DBA_DATA_FILES;

SELECT FILE_NAME, TABLESPACE_NAME, BYTES/1024/1024 AS SIZE_MB, AUTOEXTENSIBLE 
FROM DBA_TEMP_FILES;

-- 4
CREATE ROLE C##RL_GAFCORE;
GRANT CONNECT TO C##RL_GAFCORE;
GRANT CREATE TABLE, ALTER ANY TABLE, DROP ANY TABLE TO C##RL_GAFCORE;
GRANT CREATE VIEW, DROP ANY VIEW TO C##RL_GAFCORE;
GRANT CREATE PROCEDURE, ALTER ANY PROCEDURE, DROP ANY PROCEDURE TO C##RL_GAFCORE;

-- 5
SELECT * FROM DBA_ROLES WHERE ROLE = 'C##RL_GAFCORE';

SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE = 'C##RL_GAFCORE';

-- 6
CREATE PROFILE C##PF_GAFCORE LIMIT
    PASSWORD_LIFE_TIME 180
    SESSIONS_PER_USER 3
    FAILED_LOGIN_ATTEMPTS 7
    PASSWORD_LOCK_TIME 1
    PASSWORD_REUSE_TIME 10
    PASSWORD_GRACE_TIME DEFAULT
    CONNECT_TIME 180
    IDLE_TIME 30;
    
-- 7
SELECT PROFILE FROM dba_profiles;
SELECT * FROM dba_profiles WHERE PROFILE = 'C##PF_GAFCORE';

-- 8
CREATE USER C##GAFCORE
    DEFAULT TABLESPACE TS_GAF
    TEMPORARY TABLESPACE TS_GAF_TEMP
    PROFILE C##PF_GAFCORE
    ACCOUNT UNLOCK;
    PASSWORD EXPIRE;
    GRANT CREATE SESSION TO C##GAFCORE;
        
DROP USER C##GAFCORE;

-- 9
sqlplus sys as sysdba

ALTER USER C##GAFCORE IDENTIFIED BY Gibadulina;
EXIT;

sqlplus C##GAFCORE/Gibadulina

-- 10
CREATE TABLE GAF_T (
    ID INT PRIMARY KEY,
    Name VARCHAR(100),
    Location VARCHAR(100),
    Price INT
);

INSERT INTO GAF_T (ID, Name, Location, Price) 
VALUES (1, 'Yacht Club A', 'Lake A', 150);

INSERT INTO GAF_T (ID, Name, Location, Price) 
VALUES (2, 'Yacht Club B', 'Lake B', 200);

INSERT INTO GAF_T (ID, Name, Location, Price) 
VALUES (3, 'Yacht Club C', 'Lake C', 250);

INSERT INTO GAF_T (ID, Name, Location, Price) 
VALUES (4, 'Yacht Club D', 'Lake D', 300);

INSERT INTO GAF_T (ID, Name, Location, Price) 
VALUES (5, 'Yacht Club E', 'Lake E', 350);

-- 11
CREATE TABLESPACE GAF_QDATA
DATAFILE 'C:\5sem\database\GAF_QDATA.dbf' SIZE 10M 
OFFLINE;

ALTER TABLESPACE GAF_QDATA ONLINE;

ALTER USER C##GAFCORE QUOTA 2M ON GAF_QDATA;

CREATE TABLE GAF_T1 (
    ID INT PRIMARY KEY,
    DESCRIPTION VARCHAR(200)
) TABLESPACE GAF_QDATA;

INSERT INTO GAF_T1 VALUES (1, 'First record');
INSERT INTO GAF_T1 VALUES (2, 'Second record');
INSERT INTO GAF_T1 VALUES (3, 'Third record');
