--1
SELECT tablespace_name, file_name FROM dba_data_files;
SELECT tablespace_name, file_name FROM dba_temp_files;

--2
CREATE TABLESPACE GAF_QDATA 
DATAFILE 'GAA_QDATA.dbf' SIZE 10M 
OFFLINE;
SELECT tablespace_name, status FROM dba_tablespaces WHERE tablespace_name='GAF_QDATA';

ALTER TABLESPACE GAF_QDATA ONLINE;
SELECT tablespace_name, status FROM dba_tablespaces WHERE tablespace_name='GAF_QDATA';

GRANT CONNECT, RESOURCE TO C##GAF;
ALTER USER C##GAF QUOTA 2M ON GAF_QDATA;

CREATE TABLE GAF_T1 (
    ID NUMBER PRIMARY KEY,
    DATA VARCHAR2(100)
) TABLESPACE GAF_QDATA;

INSERT INTO GAF_T1 (ID, DATA) VALUES (10003, 'Data 1');
INSERT INTO GAF_T1 (ID, DATA) VALUES (20003, 'Data 2');
INSERT INTO GAF_T1 (ID, DATA) VALUES (30003, 'Data 3');

commit;

--3
SELECT SEGMENT_NAME, SEGMENT_TYPE, TABLESPACE_NAME
FROM DBA_SEGMENTS
WHERE TABLESPACE_NAME = 'GAF_QDATA';

SELECT SEGMENT_NAME, SEGMENT_TYPE, TABLESPACE_NAME FROM DBA_SEGMENTS;

--4
DROP TABLE GAF_T1;

SELECT SEGMENT_NAME, SEGMENT_TYPE, TABLESPACE_NAME
FROM DBA_SEGMENTS
WHERE TABLESPACE_NAME = 'GAF_QDATA';

SELECT * FROM USER_RECYCLEBIN;

--5
FLASHBACK TABLE GAF_T1 TO BEFORE DROP;

--6
TRUNCATE TABLE GAF_T1;
BEGIN
  FOR i IN 1..10000 LOOP
    INSERT INTO GAF_T1 (ID, DATA) 
    VALUES (i, 'Data ' || i);
  END LOOP;
  COMMIT;
END;

--7
SELECT SEGMENT_NAME, EXTENT_ID, FILE_ID, BLOCK_ID, BLOCKS, BYTES
FROM DBA_EXTENTS
WHERE SEGMENT_NAME = 'GAF_T1'
  AND TABLESPACE_NAME = 'GAF_QDATA'
ORDER BY EXTENT_ID;

--8
DROP TABLESPACE GAF_QDATA INCLUDING CONTENTS AND DATAFILES;

--9
SELECT GROUP#, STATUS, MEMBERS FROM V$LOG;

--10
SELECT GROUP#, MEMBER FROM V$LOGFILE;

--11
SELECT CURRENT_TIMESTAMP from dual;--12.11.25 18:40:25,876000000 EUROPE/MINSK
ALTER SYSTEM SWITCH LOGFILE; 
ALTER SYSTEM SWITCH LOGFILE;
ALTER SYSTEM SWITCH LOGFILE;

--12
ALTER DATABASE ADD LOGFILE GROUP 4 'C:\5sem\database\logfile1.log' SIZE 50M BLOCKSIZE 512;
ALTER DATABASE ADD LOGFILE MEMBER 'C:\5sem\database\logfile2.log' to GROUP 4;
ALTER DATABASE ADD LOGFILE MEMBER 'C:\5sem\database\logfile3.log' to GROUP 4;

SELECT GROUP#, STATUS, MEMBERS
FROM V$LOG;

SELECT GROUP#, MEMBER
FROM V$LOGFILE;

ALTER SYSTEM SWITCH LOGFILE;
SELECT group#, status, sequence# FROM v$log;
SELECT CURRENT_SCN FROM V$DATABASE;
SELECT THREAD#, SEQUENCE#, FIRST_CHANGE# FROM V$LOG;

--13
ALTER SYSTEM SWITCH LOGFILE;
ALTER SYSTEM CHECKPOINT
ALTER DATABASE DROP LOGFILE MEMBER  'C:\5sem\database\logfile1.log';
ALTER DATABASE DROP LOGFILE MEMBER  'C:\5sem\database\logfile2.log';
ALTER DATABASE DROP LOGFILE MEMBER  'C:\5sem\database\logfile3.log';
ALTER DATABASE DROP LOGFILE GROUP 4;

--14
SELECT LOG_MODE FROM V$DATABASE;

--15
SELECT MAX(SEQUENCE#) AS LAST_ARCHIVE_SEQUENCE
FROM V$ARCHIVED_LOG;
--
--16 cmd sqlplus / as sysdba
--SHUTDOWN IMMEDIATE;
--STARTUP MOUNT;
--ALTER DATABASE ARCHIVELOG;
--ALTER DATABASE OPEN;
SELECT LOG_MODE FROM V$DATABASE;

--17
SELECT * FROM V$LOG;
ALTER SYSTEM ARCHIVE LOG CURRENT;
SELECT SEQUENCE#, NAME FROM V$ARCHIVED_LOG;
SELECT * FROM V$ARCHIVED_LOG;
SELECT SEQUENCE#, FIRST_CHANGE#, NEXT_CHANGE# FROM V$ARCHIVED_LOG;

--18 cmd sqlplus / as sysdba
SHUTDOWN IMMEDIATE;
STARTUP MOUNT;
ALTER DATABASE NOARCHIVELOG;
ALTER DATABASE OPEN;

SELECT log_mode FROM v$database;

--19
SELECT NAME FROM V$CONTROLFILE;

--20
show parameter control;
SELECT TYPE, RECORDS_TOTAL, RECORDS_USED 
FROM V$CONTROLFILE_RECORD_SECTION;

--21
SHOW PARAMETER spfile;

--22
CREATE PFILE = 'C:\5sem\database\GAF_PFILE.ORA' FROM SPFILE;

--23 
select * from V$PWFILE_USERS;
SHOW PARAMETER remote_login_passwordfile;

--24
SHOW PARAMETER diagnostic_dest;

--25
SELECT NAME, VALUE FROM V$DIAG_INFO WHERE NAME = 'Diag Alert';



