--1
SELECT PDB_ID, PDB_NAME, STATUS
FROM CDB_PDBS;

--2
SELECT INSTANCE_NAME, HOST_NAME, STATUS
FROM GV$INSTANCE;

--3
SELECT PRODUCT AS Компонент, VERSION AS Версия, STATUS AS Статус
FROM PRODUCT_COMPONENT_VERSION;

--5 
SELECT PDB_ID, PDB_NAME, STATUS
FROM CDB_PDBS;

--6
ALTER SESSION SET CONTAINER=CDB$ROOT;
ALTER PLUGGABLE DATABASE GAF_PDB OPEN;
ALTER SESSION SET CONTAINER = GAF_PDB;
ALTER USER U1_GAF_PDB QUOTA UNLIMITED ON TS_GAF_PDB;
  
CREATE TABLESPACE TS_GAF_PDB 
    DATAFILE 'C:\5sem\database\TS_GAF_PDB.dbf' 
    SIZE 100M 
    AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;

CREATE ROLE RL_GAF_PDB;
GRANT CREATE SESSION,
    CREATE TABLE,
    CREATE VIEW,
    CREATE PROCEDURE
    TO RL_GAF_PDB;

CREATE PROFILE PF_GAF_PDB LIMIT 
    SESSIONS_PER_USER 5 
    FAILED_LOGIN_ATTEMPTS 3 
    PASSWORD_LIFE_TIME 30;


CREATE USER U_GAF_PDB IDENTIFIED BY 12345
    DEFAULT TABLESPACE TS_GAF_PDB
    TEMPORARY TABLESPACE TEMP
    PROFILE PF_GAF_PDB;
    GRANT RL_GAF_PDB TO U_GAF_PDB;

--7
ALTER USER U_GAF_PDB QUOTA 100M ON TS_GAF_PDB;
GRANT CREATE SESSION TO U_GAF_PDB;
GRANT CREATE TABLE TO U_GAF_PDB;
GRANT INSERT ON GAF_TABLE TO U_GAF_PDB;

CREATE TABLE GAF_TABLE (
    id NUMBER PRIMARY KEY,
    name VARCHAR2(100)
);

INSERT INTO GAF_TABLE (id, name) VALUES (1, 'Item1');
INSERT INTO GAF_TABLE (id, name) VALUES (2, 'Item2');
INSERT INTO GAF_TABLE (id, name) VALUES (3, 'Item3');
SELECT * FROM GAF_TABLE;

--8
ALTER pluggable database GAF_PBD open;
SELECT TABLESPACE_NAME, STATUS, CONTENTS FROM DBA_TABLESPACES;

SELECT FILE_NAME, TABLESPACE_NAME, BYTES, MAXBYTES 
FROM DBA_DATA_FILES;

SELECT FILE_NAME, TABLESPACE_NAME, BYTES, MAXBYTES 
FROM DBA_TEMP_FILES;

SELECT ROLE FROM DBA_ROLES;

SELECT GRANTEE, PRIVILEGE, TABLE_NAME
FROM DBA_TAB_PRIVS
WHERE GRANTEE IN (SELECT ROLE FROM DBA_ROLES);

SELECT PROFILE, RESOURCE_NAME, LIMIT FROM DBA_PROFILES;

SELECT USERNAME, ACCOUNT_STATUS FROM DBA_USERS;
SELECT GRANTEE FROM DBA_ROLE_PRIVS;

--9
ALTER SESSION SET CONTAINER=CDB$ROOT;

CREATE USER C##GAF IDENTIFIED BY Gibadulina CONTAINER=ALL;
GRANT CONNECT, RESOURCE TO C##GAF CONTAINER=ALL;
GRANT CREATE SESSION TO C##GAF CONTAINER=ALL;

--10
ALTER PLUGGABLE DATABASE GAF_PDB CLOSE IMMEDIATE;

DROP PLUGGABLE DATABASE GAF_PDB INCLUDING DATAFILES;
DROP USER C##GAF CASCADE;

--
DROP USER U_GAF_PDB CASCADE;
DROP ROLE RL_GAF_PDB;
DROP PROFILE PF_GAF_PDB CASCADE;
DROP TABLESPACE TS_GAF_PDB INCLUDING CONTENTS AND DATAFILES;